version: '3.2'

services:
    mongodb:
        image: mongo:5.0.24
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

volumes:
    mongodb_data_container: 